// Generated by CoffeeScript 1.3.3
(function() {

  (function($) {
    return $.fn.reform = function() {
      return console.log('reform: ' + $(this).attr('id'));
    };
  })(jQuery);

}).call(this);
